name: Docker Image CI

on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: scripts/cli.dockerfile
            image: shipai/boa-cli
          - dockerfile: scripts/task_gpu.dockerfile
            image:  shipai/boa-task-gpu
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup env vars
        run: |
          source ./scripts/generate_version.sh
          mkdir weights
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: false
          env:
            GIT_VERSION: ${{ env.GIT_VERSION }}
            PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          build-args: |
            GIT_VERSION=${GIT_VERSION}
            PACKAGE_VERSION=${PACKAGE_VERSION}
          tags: |
            ${{ matrix.image }}:latest
            ${{ matrix.image }}:${{ PACKAGE_VERSION }}
